sudo: required
language: go
go:
  - 1.11

services:
  - docker

jobs:
  include:
  - stage: test
    script:
      - go get -u golang.org/x/lint/golint
      - make all
  - stage: docker
    script:
      - docker run --rm --priviledged multiarch/qemu-user-static:register --reset
      - make docker
      - make docker-arm
    if: branch = master

after_success:
  - ./.travis_docker_push.sh
